[project]
name = "power-portfolio-analysis"
version = "0.1.0"
description = "Power Generation Portfolio Analysis Crew"
authors = [{ name = "lin-ggyy", email = "3320731059@qq.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.14.4"
]

[project.scripts]
crewai = "power_portfolio_analysis.main:run"
run_crew = "power_portfolio_analysis.main:run"
train = "power_portfolio_analysis.main:train"
replay = "power_portfolio_analysis.main:replay"
test = "power_portfolio_analysis.main:test"
run_with_trigger = "power_portfolio_analysis.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
